---
- name: "short open tag"
  become: yes
  lineinfile:
    dest: "{{ php_cli_config_path }}"
    regexp: "^;?short_open_tag ="
    line: "short_open_tag = {{ php_cli_short_open_tag }}"
    state: present

- name: "expose php"
  become: yes
  lineinfile:
    dest: "{{ php_cli_config_path }}"
    regexp: "^;?expose_php ="
    line: "expose_php = {{ php_cli_expose_php }}"
    state: present

- name: "max execution time"
  become: yes
  lineinfile:
    dest: "{{ php_cli_config_path }}"
    regexp: "^;?max_execution_time ="
    line: "max_execution_time = {{ php_cli_max_execution_time }}"
    state: present

- name: "max input time"
  become: yes
  lineinfile:
    dest: "{{ php_cli_config_path }}"
    regexp: "^;?max_input_time ="
    line: "max_input_time = {{ php_cli_max_input_time }}"
    state: present

- name: "memory limit"
  become: yes
  lineinfile:
    dest: "{{ php_cli_config_path }}"
    regexp: "^;?memory_limit ="
    line: "memory_limit = {{ php_cli_memory_limit }}"
    state: present

- name: "error reporting"
  become: yes
  lineinfile:
    dest: "{{ php_cli_config_path }}"
    regexp: "^;?error_reporting ="
    line: "error_reporting = {{ php_cli_error_reporting }}"
    state: present

- name: "display errors"
  become: yes
  lineinfile:
    dest: "{{ php_cli_config_path }}"
    regexp: "^;?display_errors ="
    line: "display_errors = {{ php_cli_display_errors }}"
    state: present

- name: "display startup errors"
  become: yes
  lineinfile:
    dest: "{{ php_cli_config_path }}"
    regexp: "^;?display_startup_errors ="
    line: "display_startup_errors = {{ php_cli_display_startup_errors }}"
    state: present

- name: "track errors"
  become: yes
  lineinfile:
    dest: "{{ php_cli_config_path }}"
    regexp: "^;?track_errors ="
    line: "track_errors = {{ php_cli_track_errors }}"
    state: present

- name: "html errors"
  become: yes
  lineinfile:
    dest: "{{ php_cli_config_path }}"
    regexp: "^;?html_errors ="
    line: "html_errors = {{ php_cli_html_errors }}"
    state: present

- name: "variables order"
  become: yes
  lineinfile:
    dest: "{{ php_cli_config_path }}"
    regexp: "^;?variables_order ="
    line: 'variables_order = "{{ php_cli_variables_order }}"'
    state: present

- name: "request order"
  become: yes
  lineinfile:
    dest: "{{ php_cli_config_path }}"
    regexp: "^;?request_order ="
    line: 'request_order = "{{ php_cli_request_order }}"'
    state: present

- name: "post max size"
  become: yes
  lineinfile:
    dest: "{{ php_cli_config_path }}"
    regexp: "^;?post_max_size ="
    line: "post_max_size = {{ php_cli_post_max_size }}"
    state: present

- name: "default mimetype"
  become: yes
  lineinfile:
    dest: "{{ php_cli_config_path }}"
    regexp: "^;?default_mimetype ="
    line: 'default_mimetype = "{{ php_cli_default_mimetype }}"'
    state: present

- name: "default charset"
  become: yes
  lineinfile:
    dest: "{{ php_cli_config_path }}"
    regexp: "^;?default_charset ="
    line: 'default_charset = "{{ php_cli_default_charset }}"'
    state: present

- name: "upload max filesize"
  become: yes
  lineinfile:
    dest: "{{ php_cli_config_path }}"
    regexp: "^;?upload_max_filesize ="
    line: "upload_max_filesize = {{ php_cli_upload_max_filesize }}"
    state: present

- name: "max file uploads"
  become: yes
  lineinfile:
    dest: "{{ php_cli_config_path }}"
    regexp: "^;?max_file_uploads ="
    line: "max_file_uploads = {{ php_cli_max_file_uploads }}"
    state: present

- name: "php default timezone"
  become: yes
  lineinfile:
    dest: "{{ php_cli_config_path }}"
    regexp: "^;?date.timezone ="
    line: "date.timezone = {{ php_cli_date_timezone }}"
    state: present

- name: "default include path"
  become: yes
  lineinfile:
    dest: "{{ php_cli_config_path }}"
    regexp: '^;?include_path = "\.:/'
    line: 'include_path = "{{ php_cli_include_path }}"'
    state: present
  when: php_cli_enable_includes

- name: "assertions enabled"
  become: yes
  lineinfile:
    dest: "{{ php_cli_config_path }}"
    regexp: "^;?zend.assertions ="
    line: "zend.assertions = {{ php_cli_assert_enable }}"
    state: present

- name: "assertion exceptions"
  become: yes
  lineinfile:
    dest: "{{ php_cli_config_path }}"
    regexp: "^;?assert.exception ="
    line: "assert.exception = {{ php_cli_assert_exception }}"
    state: present

- name: "extra settings"
  become: yes
  lineinfile:
    dest: "{{ php_cli_config_path }}"
    line: "{{ item.setting }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ php_cli_extra_settings }}"
  when: item.setting is defined
