---
- name: "swap space"
  become: yes
  command: |
    {% if swap_use_dd %}
    dd if=/dev/zero of={{ swap_file }} bs=1M count={{ swap_size }}
    {% else %}
    fallocate -l {{ swap_size }}M {{ swap_file }}
    {% endif %}
  args:
    creates: "{{ swap_file }}"
  register: swap_write
  when: swap_size != false

- name: "swap permissions"
  become: yes
  file:
    dest: "{{ swap_file }}"
    owner: "root"
    group: "root"
    mode: "0600"
  when: swap_size != false

- name: "make swap"
  become: yes
  command: "mkswap {{ swap_file }}"
  register: swap_make
  when: swap_size != false and swap_write.changed

- name: "enable swap"
  become: yes
  command: "swapon {{ swap_file }}"
  when: swap_size != false and swap_make.changed

- name: "swap fstab"
  become: yes
  lineinfile:
    dest: "/etc/fstab"
    line: "{{ swap_file }}   none    swap   sw    0   0"
    state: present
  when: swap_size != false

- name: "swappiness"
  become: yes
  sysctl:
    name: "vm.swappiness"
    value: "{{ swap_swappiness }}"
    state: present
    reload: yes
  when: swap_swappiness != false

- name: "vfs cache pressure"
  become: yes
  sysctl:
    name: "vm.vfs_cache_pressure"
    value: "{{ swap_vfs_cache_pressure }}"
    state: present
    reload: yes
  when: swap_vfs_cache_pressure != false
