---
- name: "base packages"
  become: yes
  apt:
    name: "{{ item.name }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  with_items: "{{ app_packages }}"
  when: item.name is defined
