---
- include: "base.yml"
- include: "gitconfig.yml"

- name: "vagrant directory change"
  lineinfile:
    dest: "/home/{{ ansible_user_id }}/.bashrc"
    line: "cd /vagrant"
    state: present

- name: "composer install"
  composer:
    command: "install"
    working_dir: "{{ app_root_dir }}"
    no_dev: false
    optimize_autoloader: false
