---
- name: "autoremove"
  become: yes
  command: "apt-get -y autoremove"

- name: "autoclean"
  become: yes
  command: "apt-get -y autoclean"

- name: "clean packages"
  become: yes
  command: "apt-get -y clean"

- name: "update grub"
  become: yes
  command: "update-grub"
  when: upgrade_update_grub
