---
- name: "system timezone"
  become: yes
  file:
    src: "/usr/share/zoneinfo/{{ time_system_timezone }}"
    dest: "/etc/localtime"
    state: link
    force: yes

- name: "ntp installed"
  become: yes
  apt:
    name: "ntp"
    state: present

- name: "ntp enabled"
  become: yes
  service:
    name: "ntp"
    state: started
    enabled: yes
  when: time_ntp_enabled

- name: "ntp disabled"
  become: yes
  service:
    name: "ntp"
    state: stopped
    enabled: no
  when: not time_ntp_enabled
