---
# policies: "ACCEPT", "DROP", or "REJECT"
firewall_policy_input: "DROP"
firewall_policy_forward: "DROP"
firewall_policy_output: "ACCEPT"
firewall_log_dropped_packets: true
firewall_ssh_port: 22
firewall_allowed_tcp_ports: [80, 443]
firewall_allowed_udp_ports: []
# firewall_forwarded_tcp_ports:
# - src: 8080                                    #required
#   dest: 80                                     #required
firewall_forwarded_tcp_ports: []
# firewall_forwarded_udp_ports:
# - src: 8080                                    #required
#   dest: 80                                     #required
firewall_forwarded_udp_ports: []
firewall_additional_rules: []
